name: Despliegue a surge.sh

on:
  push:
    branches:
      - master  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install  

    # Instalar Surge globalmente
    - name: Install Surge
      run: npm install --global surge

    - name: Deploy to Surge
      env:
        SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
      run: |
        surge ./ yohendry-primer.surge.sh --token $SURGE_TOKEN